name: Build Artifact
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod
      - run: |
          chmod +x ./build.sh
          ./build.sh ${{ vars.DIST_NAME }}
      - uses: actions/upload-artifact@v4
        with:
          name: bad-proxy-core
          path: dist
          overwrite: true
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'dist/**/*.tar.gz, dist/**/*.zip'
