name: Checking build
permissions:
  contents: read
on:
  pull_request:
    branches:
      - master
      - release
  workflow_dispatch:
jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod
      - run: go build -o bad_proxy
